### ISSUE TITLE
Tweet download ends too early when there are plainly more tweets available

### ISSUE THREAD

**Issue by minimaxir** [minimaxir/download-tweets-ai-text-gen#2]
The datetime output at the end of the query makes this evident when it occurs.

Most likely a `twint` issue but need to see if there is a workaround for specific use cases.

**Comment by minimaxir** [comment]
It appears it may be somewhat due to time/IP? Accounts that were working yesterday for me are not working now (die after ~100 tweets)

**Comment by minimaxir** [comment]
It's def an issue with `twint`: running the base `twint` command w/ no special parameters causes the issue as well.

**Comment by minimaxir** [comment]
After testing, the implementation in 3106f72d5a8cdc1c300a1b1fcd265fee3be30708 avoids this issue, although at a slight performance/code readability cost. Will have to see if there is a better implementation.

**Comment by mmolaro** [comment]
Twitter may have added some more antiscraping methods/throttling. I can't seem to get more than 5-700 KB of data. Increasing the sleep to 60s isn't enough either.

**Comment by diwakergupta** [comment]
Same here, download consistently stops after downloading ~200-KB worth of tweets. Exit code is 0 though, so it doesn't seem like the script is erroring out.

**Comment by minimaxir** [comment]
To clarify, this is with `twint=2.1.4` correct? This issue happened with more recent versions.

**Comment by mmolaro** [comment]
Yes with twint=2.1.4 looking at twint repo issues seems like the issue is there across a range of versions.

**Comment by diwakergupta** [comment]
FWIW, using the `twint` cli directly I was able to get twice as many tweets (~7000 vs. ~14000). 🤷‍♂
