### ISSUE TITLE
Google Colab GPT-2 tweets no different than the input

### ISSUE THREAD

**Issue by walter-grace** [minimaxir/download-tweets-ai-text-gen#31]
I seem to load the csv file from using the python code, I am using 1000 tweets and the only results are just printing out tweets I gave it vs running putting out GANs tweets. Do I maybe need to use more tweets?

**Comment by sdelgadoc** [comment]
Yup, 1,000 tweets is on the low side. There is no hard and fast rule, but I’ve heard folks get decent results once they reach 1MB size, which is about 30,000 tweets.

**Comment by walter-grace** [comment]
Will this py file work by itself? Id love to run this in colab with a GPU for faster trainning

**Comment by walter-grace** [comment]
> Yup, 1,000 tweets is on the low side. There is no hard and fast rule, but I’ve heard folks get decent results once they reach 1MB size, which is about 30,000 tweets.
@sdelgadoc 
I Will try larger dataset, do you know if this py file work by itself? Id love to run this in colab with a GPU for faster trainning

**Comment by sdelgadoc** [comment]
Yes, this script could run in a Colab. However, I doubt you’ll see an increase in performance. The performance constraint is Twitter’s data transfer rate not processing power.  So, I don’t believe that adding a GPU will make it run faster.

**Comment by walter-grace** [comment]
> Yes, this script could run in a Colab. However, I doubt you’ll see an increase in performance. The performance constraint is Twitter’s data transfer rate not processing power. So, I don’t believe that adding a GPU will make it run faster.

Wonderful thank you for the help
